### PR TITLE
klte: Remove FPS Blobs

### PR DESCRIPTION
**Pull request by javelinanddart**
- We're using a fully OSS stack now

Signed-off-by: Paul Keith javelinanddart@gmail.com

### CODE REVIEW

**Comment by javelinanddart** [comment]
Depends on https://review.slimroms.org/#/c/20658 & https://review.slimroms.org/#/c/20659

**Comment by PRJosh** [comment]
So is this good to merge or not?

Josué Rivera

**Comment by javelinanddart** [comment]
I want to wait for more testing, I'll ask when I need it merged @PRJosh

**Comment by javelinanddart** [comment]
@PRJosh This is good to go

**Pull request merged**
